# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#vowel sounds
Sound.create(sound: "i", sound_type: "vowel")
Sound.create(sound: "y", sound_type: "vowel")
Sound.create(sound: "ɨ", sound_type: "vowel")
Sound.create(sound: "ʉ", sound_type: "vowel")
Sound.create(sound: "ɯ", sound_type: "vowel")
Sound.create(sound: "U", sound_type: "vowel")
Sound.create(sound: "I", sound_type: "vowel")
Sound.create(sound: "Y", sound_type: "vowel")
Sound.create(sound: "ʊ", sound_type: "vowel")
Sound.create(sound: "e", sound_type: "vowel")
Sound.create(sound: "ø", sound_type: "vowel")
Sound.create(sound: "ɘ", sound_type: "vowel")
Sound.create(sound: "ɵ", sound_type: "vowel")
Sound.create(sound: "ɤ", sound_type: "vowel")
Sound.create(sound: "o", sound_type: "vowel")
Sound.create(sound: "ə", sound_type: "vowel")
Sound.create(sound: "ɛ", sound_type: "vowel")
Sound.create(sound: "œ", sound_type: "vowel")
Sound.create(sound: "ɜ", sound_type: "vowel")
Sound.create(sound: "ɞ", sound_type: "vowel")
Sound.create(sound: "ʌ", sound_type: "vowel")
Sound.create(sound: "ɔ", sound_type: "vowel")
Sound.create(sound: "ɐ", sound_type: "vowel")
Sound.create(sound: "æ", sound_type: "vowel")
Sound.create(sound: "a", sound_type: "vowel")
Sound.create(sound: "ɶ", sound_type: "vowel")
Sound.create(sound: "ɑ", sound_type: "vowel")
Sound.create(sound: "ɒ", sound_type: "vowel")

#consonant sounds
Sound.create(sound: "p", sound_type: "consonant")
Sound.create(sound: "b", sound_type: "consonant")
Sound.create(sound: "m", sound_type: "consonant")
Sound.create(sound: "ʙ", sound_type: "consonant")
Sound.create(sound: "ɸ", sound_type: "consonant")
Sound.create(sound: "β", sound_type: "consonant")
Sound.create(sound: "ɱ", sound_type: "consonant")
Sound.create(sound: "ⱱ", sound_type: "consonant")
Sound.create(sound: "f", sound_type: "consonant")
Sound.create(sound: "v", sound_type: "consonant")
Sound.create(sound: "ʋ", sound_type: "consonant")
Sound.create(sound: "t", sound_type: "consonant")
Sound.create(sound: "θ", sound_type: "consonant")
Sound.create(sound: "ð", sound_type: "consonant")
Sound.create(sound: "s", sound_type: "consonant")
Sound.create(sound: "ɬ", sound_type: "consonant")
Sound.create(sound: "d", sound_type: "consonant")
Sound.create(sound: "n", sound_type: "consonant")
Sound.create(sound: "r", sound_type: "consonant")
Sound.create(sound: "ɾ", sound_type: "consonant")
Sound.create(sound: "z", sound_type: "consonant")
Sound.create(sound: "ʃ", sound_type: "consonant")
Sound.create(sound: "ʒ", sound_type: "consonant")
Sound.create(sound: "ɮ", sound_type: "consonant")
Sound.create(sound: "ɹ", sound_type: "consonant")
Sound.create(sound: "l", sound_type: "consonant")
Sound.create(sound: "ʈ", sound_type: "consonant")
Sound.create(sound: "ɖ", sound_type: "consonant")
Sound.create(sound: "ɳ", sound_type: "consonant")
Sound.create(sound: "ɽ", sound_type: "consonant")
Sound.create(sound: "ʂ", sound_type: "consonant")
Sound.create(sound: "ʐ", sound_type: "consonant")
Sound.create(sound: "ɻ", sound_type: "consonant")
Sound.create(sound: "ɭ", sound_type: "consonant")
Sound.create(sound: "c", sound_type: "consonant")
Sound.create(sound: "ɟ", sound_type: "consonant")
Sound.create(sound: "ɲ", sound_type: "consonant")
Sound.create(sound: "ç", sound_type: "consonant")
Sound.create(sound: "ʝ", sound_type: "consonant")
Sound.create(sound: "j", sound_type: "consonant")
Sound.create(sound: "ʎ", sound_type: "consonant")
Sound.create(sound: "k", sound_type: "consonant")
Sound.create(sound: "g", sound_type: "consonant")
Sound.create(sound: "ŋ", sound_type: "consonant")
Sound.create(sound: "x", sound_type: "consonant")
Sound.create(sound: "ɣ", sound_type: "consonant")
Sound.create(sound: "ɰ", sound_type: "consonant")
Sound.create(sound: "ʟ", sound_type: "consonant")
Sound.create(sound: "q", sound_type: "consonant")
Sound.create(sound: "ɢ", sound_type: "consonant")
Sound.create(sound: "ɴ", sound_type: "consonant")
Sound.create(sound: "ʀ", sound_type: "consonant")
Sound.create(sound: "χ", sound_type: "consonant")
Sound.create(sound: "ʁ", sound_type: "consonant")
Sound.create(sound: "ħ", sound_type: "consonant")
Sound.create(sound: "ʕ", sound_type: "consonant")
Sound.create(sound: "ʔ", sound_type: "consonant")
Sound.create(sound: "h", sound_type: "consonant")
Sound.create(sound: "ɦ", sound_type: "consonant")
